---
title: "Presentations"
subtitle: "(including scheduled)"
---

&nbsp;

#### **Jan 2019**

- Southern Political Science Association (SPAS) conference, Austin, TX.

#### **Nov 2018**

- Université Paris-Dauphine, Paris.

- Data Natives, Berlin.

- Artificial Intelligence International Conference (A2IC) conference, Barcelona.

- Midwest Association for Public Opinion Research (MAPOR) conference, Chicago, IL.

- International Studies Association - ISSS (ISA-ISSS) conference, West Lafayette, IN.

#### **Oct 2018**

- Regulatory Studies Center, George Washington University.

- TEXATA Summit: Big Data Analytics Conference of Texas, Austin, TX. ([**slides**](http://www.policychangeindex.com/Reading_China_slides_TEXATA.pdf))

- International Conference on Communication & Media Studies (ICCMS), Berkeley, CA. ([**slides**](http://www.policychangeindex.com/Reading_China_slides_ICCMS.pdf))

- International Studies Association - South (ISA-South) conference, Ashland, VA.

- Association of Chinese Political Studies (ACPS) conference, Harrisonburg, VA.

- American Association for Chinese Studies (AACS) conference, Baltimore, MD.

#### **Sep 2018**

- Center for Micro-Economic Policy Research, George Mason University.